version: "3.9"

services:
  upload:
    build:
      context: ./Backend/upload
      dockerfile: Dockerfile.upload
    container_name: service-upload
    networks:
      - mynet
    ports:
      - "8000"
    volumes:
      - ./uploads:/uploads
    environment:
      - FORWARD_URL=http://parse:8001/parse_resume/
      - UPLOAD_DIR=/uploads
    depends_on:
      - parse

  parse:
    build:
      context: ./Backend/parse
      dockerfile: Dockerfile.parse
    container_name: service-parse
    networks:
      - mynet
    volumes:
      - ./uploads:/uploads
    environment:
      - UPLOAD_DIR=/uploads
      - ENHANCE_URL=http://enhance:8002/enhance_resume/
    ports:
      - "8001"
    depends_on:
      - enhance

  enhance:
    build:
      context: ./Backend/enhance
      dockerfile: Dockerfile.enhance
    container_name: service-enhance
    networks:
      - mynet
    volumes:
      - ./uploads:/uploads
    ports:
      - "8002"
    environment:
      - GROQ_API_KEY=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
      - GROQ_URL=https://api.groq.com/openai/v1/chat/completions
      - UPLOAD_DIR=/uploads
      - GENERATED_DIR=/generated_pdfs



  webapp:
    build: ./Frontend/my-app
    networks:
      - mynet
    ports:
      - "3000"
    environment:
      - REACT_APP_UPLOAD_URL=http://127.0.0.1
      # - REACT_APP_PDF_URL=http://pdf-service:8003
    volumes:
      - ./Frontend/my-app:/app
      - /app/node_modules



  nginx:
    image: nginx:latest
    container_name: gateway-nginx
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - upload
      - parse
      - enhance
      - webapp

networks:
  mynet: