FROM python:3.11-slim
WORKDIR /app
COPY requirements.upload.txt .
RUN pip install --no-cache-dir -r requirements.upload.txt
COPY Service_upload.py .
RUN mkdir -p /uploads
EXPOSE 8000
CMD ["uvicorn", "Service_upload:app", "--host", "0.0.0.0", "--port", "8000"]
