FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libmupdf-dev
COPY requirements.parse.txt .
RUN pip install --no-cache-dir -r requirements.parse.txt
COPY Service_parse.py .
EXPOSE 8001
CMD ["uvicorn", "Service_parse:app", "--host", "0.0.0.0", "--port", "8001"]
